import Navbar from "@/components/Navbar";
import Provider from "../components/Provider";
import UserFetcher from "@/components/UserFetcher";
import "./globals.css";
import { Koulen, Hammersmith_One, Sen } from "next/font/google";

const koulen = Koulen({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-koulen",
  weight: "400",
});

const hammersmith = Hammersmith_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-hammersmith",
  weight: "400",
});

const sen = Sen({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sen",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${koulen.variable} ${hammersmith.variable} ${sen.variable}`}
      >
        <Provider>
          <UserFetcher>{({ user }) => <Navbar user={user} />}</UserFetcher>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
